# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Lively' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '5.0.2'
  pod 'TwilioVideo', '~> 3.2'
  pod 'AppCenter/Distribute', '2.5.3'
  pod 'Crashlytics', '3.14.0'
  pod 'Firebase/Analytics', '6.14.0'
  pod 'FirebaseUI/Auth', '8.4.0'
  pod 'FirebaseUI/Google', '8.4.0'
  pod 'KeychainAccess', '4.1.0'

  # Pods for Lively

end
